Repository mabarnes/moment_kinetics, pull requests merged in 2023-09, with the labels that each got.

#120 Small fixes and updates for makie_post_processing
  src/makie_post_processing.jl
  src/moment_kinetics_input.jl
  src/time_advance.jl
Labels: bug, enhancement

#125 Minor bug fixes
  .github/workflows/debug_checks.yml
  src/communication.jl
  src/continuity.jl
  src/force_balance.jl
  src/initial_conditions.jl
  src/moment_constraints.jl
  src/time_advance.jl
  src/velocity_moments.jl
  src/vpa_advection.jl
Labels: bug

#126 Plot/animate the unnormalised distribution function in makie_post_processing
  src/makie_post_processing.jl
  src/post_processing.jl
  src/time_advance.jl
Labels: enhancement

#132 If a NaN is found, stop the simulation
  src/time_advance.jl
Labels: enhancement

#135 Simplify restart functionality
  README.md
  machines/README.md
  machines/archer/jobscript-restart.template
  machines/marconi/jobscript-restart.template
  restart_moment_kinetics.jl
  src/command_line_options.jl
  src/communication.jl
  src/moment_kinetics.jl
  src/post_processing.jl
  submit-restart.sh
Labels: bug, enhancement

#123 Unequally spaced element boundaries for grid optimisations
  .github/workflows/test.yml
  src/chebyshev.jl
  src/coordinates.jl
  src/file_io.jl
  src/input_structs.jl
  src/load_data.jl
  src/moment_kinetics_input.jl
  src/post_processing.jl
  test/calculus_tests.jl
  test/interpolation_tests.jl
  test/nonlinear_sound_wave_tests.jl
  test/wall_bc_tests.jl
Labels: enhancement
