Repository mabarnes/moment_kinetics, pull requests merged in 2023-11, with the labels that each got.

#127 Krook 'collisions'
  Project.toml
  docs/src/utils.md
  runs/1D-wall_MMS_new_nel_r_1_z_16_vpa_16_vperp_1_krook.toml
  runs/1D-wall_MMS_new_nel_r_1_z_16_vpa_8_vperp_8_krook.toml
  src/constants.jl
  src/file_io.jl
  src/initial_conditions.jl
  src/input_structs.jl
  src/krook_collisions.jl
  src/makie_post_processing.jl
  src/manufactured_solns.jl
  src/moment_kinetics.jl
  src/moment_kinetics_input.jl
  src/moment_kinetics_structs.jl
  src/plot_MMS_sequence.jl
  src/post_processing.jl
  src/reference_parameters.jl
  src/time_advance.jl
  src/utils.jl
  src/velocity_moments.jl
  test/Krook_collisions_tests.jl
  test/nonlinear_sound_wave_tests.jl
  test/runtests.jl
  test/velocity_integral_tests.jl
  util/compare_collision_frequencies.jl
Labels: enhancement

#128 Allow interpolation between grids when restarting
  .github/workflows/longtest.yml
  .github/workflows/parallel_test.yml
  .github/workflows/test.yml
  README.md
  docs/src/constants.md
  docs/src/krook_collisions.md
  docs/src/reference_parameters.md
  src/calculus.jl
  src/chebyshev.jl
  src/coordinates.jl
  src/finite_differences.jl
  src/hermite_spline_interpolation.jl
  src/interpolation.jl
  src/load_data.jl
  src/moment_kinetics.jl
  src/moment_kinetics_input.jl
  src/moment_kinetics_structs.jl
  test/Krook_collisions_tests.jl
  test/calculus_tests.jl
  test/harrisonthompson.jl
  test/nonlinear_sound_wave_inputs_and_expected_data.jl
  test/nonlinear_sound_wave_tests.jl
  test/restart_interpolation_tests.jl
  test/runtests.jl
  test/setup.jl
  test/sound_wave_tests.jl
  test/wall_bc_tests.jl
Labels: enhancement

#110 A generalised kinetic Chodura condition with radial dependence
  src/file_io.jl
  src/input_structs.jl
  src/load_data.jl
  src/post_processing.jl
  src/post_processing_input.jl
  src/time_advance.jl
  src/velocity_moments.jl
Labels: enhancement

#131 Save the run-time of simulations to the output file
  src/file_io.jl
  src/file_io_hdf5.jl
  src/file_io_netcdf.jl
  src/moment_kinetics.jl
  src/time_advance.jl
  src/utils.jl
Labels: enhancement

#133 Make Chodura condition check compatible with moment-kinetic modes
  src/analysis.jl
  src/makie_post_processing.jl
  src/post_processing.jl
Labels: enhancement

#142 Allow loading coordinates from files created before `element_spacing_option` was added
  src/load_data.jl
Labels: bug

#143 Energy source term
  docs/src/external_sources_notes.md
  src/continuity.jl
  src/energy_equation.jl
  src/external_sources.jl
  src/file_io.jl
  src/force_balance.jl
  src/time_advance.jl
  src/velocity_moments.jl
  test/recycling_fraction_tests.jl
Labels: enhancement

#145 `makie_post_processing` update
  docs/src/post_processing_notes.md
  src/makie_post_processing.jl
  src/moment_kinetics.jl
  test/restart_interpolation_tests.jl
Labels: bug, enhancement

#146 Update automated parameter scan functionality
  README.md
  docs/src/index.md
  docs/src/parameter_scans.md
  docs/src/zz_scan_input.md
  driver.jl
  post_process_parameter_scan.jl
  post_processing_driver.jl
  run_parameter_scan.jl
  scan_input.jl
  src/moment_kinetics.jl
  src/moment_kinetics_input.jl
  src/parameter_scans.jl
  src/scan_input.jl
  test/harrisonthompson.jl
  test/nonlinear_sound_wave_tests.jl
  test/recycling_fraction_tests.jl
  test/sound_wave_tests.jl
  test/wall_bc_tests.jl
Labels: enhancement

#150 Fix MPI linking bug; fix CI tests
  .github/workflows/debug_checks.yml
  .github/workflows/examples.yml
  .github/workflows/longtest.yml
  .github/workflows/parallel_test.yml
  .github/workflows/test.yml
  Project.toml
  debug_test/harrisonthompson.jl
  debug_test/mms_tests.jl
  debug_test/restart_interpolation_inputs.jl
  debug_test/restart_interpolation_tests.jl
  debug_test/runtest_template.jl
  debug_test/runtests.jl
  debug_test/setup.jl
  debug_test/sound_wave_tests.jl
  debug_test/wall_bc_tests.jl
  src/file_io.jl
  src/load_data.jl
  test/Krook_collisions_tests.jl
  test/harrisonthompson.jl
  test/nonlinear_sound_wave_inputs_and_expected_data.jl
  test/nonlinear_sound_wave_tests.jl
  test/recycling_fraction_tests.jl
  test/restart_interpolation_tests.jl
  test/sound_wave_tests.jl
  test/wall_bc_tests.jl
Labels: bug, tests

#155 Small documentation improvements
  README.md
  test/calculus_tests.jl
Labels: documentation

#158 Fix 'longtest' CI job
  .github/workflows/longtest.yml
  src/makie_post_processing.jl
  test/restart_interpolation_tests.jl
Labels: tests

#159 Fix use of `makie_post_processing` with NetCDF output files
  docs/src/post_processing_notes.md
  src/makie_post_processing.jl
Labels: bug
