Repository mabarnes/moment_kinetics, pull requests merged in 2024-10, with the labels that each got.

#271 Attempt to fix intermittent CI failures
  .github/workflows/longtest.yml
  .github/workflows/parallel_test.yml
  .github/workflows/test.yml
  moment_kinetics/src/command_line_options.jl
  moment_kinetics/test/setup.jl
Labels: tests

#270 Correct units for pressures to reflect normalisation used in the code.
  moment_kinetics/src/file_io.jl
Labels: documentation

#274 Fix failures of 'long tests' CI job
  moment_kinetics/test/restart_interpolation_tests.jl
Labels: tests

#277 Use parallel I/O in Github Actions CI tests
  .github/workflows/debug_checks.yml
  .github/workflows/parallel_test.yml
  moment_kinetics/Project.toml
  moment_kinetics/debug_test/sound_wave_inputs.jl
  moment_kinetics/test/harrisonthompson.jl
Labels: tests

#276 Collect and print/save timings
  docs/src/developing.md
  docs/src/zz_timer_utils.md
  makie_post_processing/makie_post_processing/Project.toml
  makie_post_processing/makie_post_processing/src/makie_post_processing.jl
  moment_kinetics/Project.toml
  moment_kinetics/ext/file_io_netcdf.jl
  moment_kinetics/src/boundary_conditions.jl
  moment_kinetics/src/calculus.jl
  moment_kinetics/src/charge_exchange.jl
  moment_kinetics/src/communication.jl
  moment_kinetics/src/continuity.jl
  moment_kinetics/src/debugging.jl
  moment_kinetics/src/electron_fluid_equations.jl
  moment_kinetics/src/electron_kinetic_equation.jl
  moment_kinetics/src/electron_vpa_advection.jl
  moment_kinetics/src/electron_z_advection.jl
  moment_kinetics/src/energy_equation.jl
  moment_kinetics/src/external_sources.jl
  moment_kinetics/src/file_io.jl
  moment_kinetics/src/file_io_hdf5.jl
  moment_kinetics/src/fokker_planck.jl
  moment_kinetics/src/force_balance.jl
  moment_kinetics/src/gyroaverages.jl
  moment_kinetics/src/ionization.jl
  moment_kinetics/src/krook_collisions.jl
  moment_kinetics/src/load_data.jl
  moment_kinetics/src/manufactured_solns.jl
  moment_kinetics/src/maxwell_diffusion.jl
  moment_kinetics/src/moment_constraints.jl
  moment_kinetics/src/moment_kinetics.jl
  moment_kinetics/src/neutral_advection.jl
  moment_kinetics/src/neutral_r_advection.jl
  moment_kinetics/src/neutral_vz_advection.jl
  moment_kinetics/src/neutral_z_advection.jl
  moment_kinetics/src/nonlinear_solvers.jl
  moment_kinetics/src/numerical_dissipation.jl
  moment_kinetics/src/r_advection.jl
  moment_kinetics/src/source_terms.jl
  moment_kinetics/src/time_advance.jl
  moment_kinetics/src/timer_utils.jl
  moment_kinetics/src/utils.jl
  moment_kinetics/src/velocity_grid_transforms.jl
  moment_kinetics/src/vpa_advection.jl
  moment_kinetics/src/vperp_advection.jl
  moment_kinetics/src/z_advection.jl
Labels: enhancement

#281 Fix a couple of small errors in the setup process
  docs/src/post_processing_notes.md
  machines/shared/machine_setup_stage_two.jl
  makie_post_processing/makie_post_processing/src/makie_post_processing.jl
Labels: bug, documentation

#279 Fix machine setup for HDF5 on macOS
  machines/shared/add_dependencies_to_project.jl
Labels: bug
