Repository mabarnes/moment_kinetics, pull requests merged in 2024-04, with the labels that each got.

#184 Make machine setup scripts work on MacOS
  machines/generic-batch-template/compile_dependencies.sh
  machines/generic-pc/compile_dependencies.sh
  machines/machine_setup.sh
  machines/marconi/compile_dependencies.sh
Labels: bug

#201 In machine_setup.sh on macOS, prompt for MPI library path
  machines/shared/add_dependencies_to_project.jl
Labels: bug

#203 Make all processes use identical FFTW plans
  moment_kinetics/src/chebyshev.jl
  moment_kinetics/src/coordinates.jl
  moment_kinetics/src/load_data.jl
  moment_kinetics/src/moment_kinetics.jl
  moment_kinetics/src/moment_kinetics_input.jl
  moment_kinetics/test/calculus_tests.jl
  moment_kinetics/test/interpolation_tests.jl
  moment_kinetics/test/velocity_integral_tests.jl
  moment_kinetics/test/wall_bc_tests.jl
Labels: bug

#187 Feature gyroaverages
  examples/gk-ions/2D-periodic-gk.toml
  makie_post_processing/makie_post_processing/src/shared_utils.jl
  moment_kinetics/debug_test/gyroaverage_inputs.jl
  moment_kinetics/debug_test/gyroaverage_tests.jl
  moment_kinetics/debug_test/runtests.jl
  moment_kinetics/src/chebyshev.jl
  moment_kinetics/src/coordinates.jl
  moment_kinetics/src/em_fields.jl
  moment_kinetics/src/gyroaverages.jl
  moment_kinetics/src/initial_conditions.jl
  moment_kinetics/src/input_structs.jl
  moment_kinetics/src/moment_kinetics.jl
  moment_kinetics/src/moment_kinetics_input.jl
  moment_kinetics/src/moment_kinetics_structs.jl
  moment_kinetics/src/r_advection.jl
  moment_kinetics/src/time_advance.jl
  moment_kinetics/src/velocity_moments.jl
  moment_kinetics/src/vpa_advection.jl
  moment_kinetics/src/z_advection.jl
  moment_kinetics/test/gyroaverage_tests.jl
  moment_kinetics/test/runtests.jl
  test_scripts/gyroaverage_test.jl
Labels: enhancement

#206 Handle updated timestepping options in restart_interpolation_tests.jl
  .github/workflows/debug_checks.yml
  .github/workflows/examples.yml
  .github/workflows/longtest.yml
  .github/workflows/parallel_test.yml
  .github/workflows/test.yml
  moment_kinetics/test/restart_interpolation_tests.jl
Labels: tests

#208 Fix some small issues with machine setup scripts
  machines/shared/add_dependencies_to_project.jl
  machines/shared/machine_setup.jl
Labels: bug
