Repository mabarnes/moment_kinetics, pull requests merged in 2024-09, with the labels that each got.

#243 "coarse_tails" option for grid spacing
  examples/recycling-fraction/wall-bc_recyclefraction0.5-init.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split1.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split2.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3-init.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_SSPRK4.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_fekete104.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_fekete42.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_fekete64.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_rkf54.toml
  moment_kinetics/src/coordinates.jl
  moment_kinetics/test/recycling_fraction_tests.jl
Labels: enhancement

#250 Multiple source functionality
  examples/fokker-planck/fokker-planck-relaxation-slowing-down-alphas.toml
  examples/fokker-planck/fokker-planck-source-sink-slowing-down-alphas-no-self-collisions.toml
  examples/fokker-planck/fokker-planck-source-sink-slowing-down-alphas.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_braginskii-vpadiss0-IMEX.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-vpadiss0.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5-init.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split1.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split2.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3-init.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_SSPRK4.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_fekete104.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_fekete42.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_fekete64.toml
  examples/recycling-fraction/wall-bc_recyclefraction0.5_split3_rkf54.toml
  examples/wall-bc/wall-bc_no-neutrals.toml
  examples/wall-bc/wall-bc_no-neutrals_split1.toml
  examples/wall-bc/wall-bc_no-neutrals_split2.toml
  examples/wall-bc/wall-bc_no-neutrals_split3.toml
  examples/wall-bc/wall-bc_volumerecycle.toml
  examples/wall-bc/wall-bc_volumerecycle_split1.toml
  examples/wall-bc/wall-bc_volumerecycle_split2.toml
  examples/wall-bc/wall-bc_volumerecycle_split3.toml
  makie_post_processing/makie_post_processing/src/makie_post_processing.jl
  moment_kinetics/debug_test/kinetic_electron_inputs.jl
  moment_kinetics/debug_test/recycling_fraction_inputs.jl
  moment_kinetics/ext/file_io_netcdf.jl
  moment_kinetics/src/continuity.jl
  moment_kinetics/src/electron_fluid_equations.jl
  moment_kinetics/src/electron_kinetic_equation.jl
  moment_kinetics/src/electron_vpa_advection.jl
  moment_kinetics/src/energy_equation.jl
  moment_kinetics/src/external_sources.jl
  moment_kinetics/src/file_io.jl
  moment_kinetics/src/file_io_hdf5.jl
  moment_kinetics/src/force_balance.jl
  moment_kinetics/src/initial_conditions.jl
  moment_kinetics/src/input_structs.jl
  moment_kinetics/src/krook_collisions.jl
  moment_kinetics/src/load_data.jl
  moment_kinetics/src/moment_kinetics_structs.jl
  moment_kinetics/src/neutral_vz_advection.jl
  moment_kinetics/src/source_terms.jl
  moment_kinetics/src/time_advance.jl
  moment_kinetics/src/velocity_moments.jl
  moment_kinetics/src/vpa_advection.jl
  moment_kinetics/test/harrisonthompson.jl
  moment_kinetics/test/recycling_fraction_tests.jl
  publication_inputs/2023_EFTC_jto-poster/wall-bc/wall-bc_recyclefraction0.5.toml
  publication_inputs/2023_EFTC_jto-poster/wall-bc/wall-bc_recyclefraction0.5_split1.toml
  publication_inputs/2023_EFTC_jto-poster/wall-bc/wall-bc_recyclefraction0.5_split2.toml
  publication_inputs/2023_EFTC_jto-poster/wall-bc/wall-bc_recyclefraction0.5_split3.toml
Labels: enhancement

#246 Add some explanation of MPISharedArray type to the docs
  docs/src/developing.md
  moment_kinetics/src/communication.jl
Labels: documentation

#255 When we catch an exception, print it to stderr before calling MPI.Abort
  moment_kinetics/src/moment_kinetics.jl
Labels: bug

#257 Reduce max output file path lengths in restart_interpolation_tests.jl
  moment_kinetics/test/restart_interpolation_tests.jl
Labels: bug, tests

#261 Read distribution function sections in moments' input_dict for makie_post_processing()
  makie_post_processing/makie_post_processing/src/makie_post_processing.jl
Labels: bug, post processing

#259 Remove mpi4py setup in parallel CI jobs
  .github/workflows/debug_checks.yml
  .github/workflows/parallel_test.yml
Labels: tests

#262 Handle errors separately for each type of plot in timestep_diagnostics()
  makie_post_processing/makie_post_processing/src/makie_post_processing.jl
  moment_kinetics/src/load_data.jl
Labels: bug, post processing

#260 Tests of the 1D ODE solvers provided by the gauss_legendre.jl module.…
  moment_kinetics/test/calculus_tests.jl
Labels: tests

#264 Use `--oversubscribe` for parallel CI jobs
  .github/workflows/debug_checks.yml
  .github/workflows/parallel_test.yml
Labels: bug, tests

#265 Fix "wall_exp_decay" source for distributed MPI
  moment_kinetics/src/external_sources.jl
Labels: bug
