Repository mabarnes/moment_kinetics, pull requests merged in 2025-01, with the labels that each got.

#230 Chebyshev documentation
  docs/src/chebyshev.md
Labels: documentation

#289 Improvement of online docs for Fokker-Planck options
  docs/src/fokker_planck_notes.md
  docs/src/index.md
  moment_kinetics/src/fokker_planck.jl
  moment_kinetics/src/fokker_planck_calculus.jl
  moment_kinetics/src/fokker_planck_test.jl
  moment_kinetics/src/gauss_legendre.jl
  test_scripts/2D_FEM_assembly_test.jl
Labels: documentation

#302 Better handling of wall boundary conditions in implicit electron timesteps
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-KennedyCarpenterARK324-wall-Jac.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-KennedyCarpenterARK324.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-compressed-z-KennedyCarpenterARK324-wall-Jac.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-compressed-z-KennedyCarpenterARK324.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-compressed-z4-KennedyCarpenterARK324-wall-Jac.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-compressed-z4-KennedyCarpenterARK324.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-uniform-z-KennedyCarpenterARK324-wall-Jac.toml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-uniform-z-KennedyCarpenterARK324.toml
  moment_kinetics/debug_test/kinetic_electron_inputs.jl
  moment_kinetics/src/chebyshev.jl
  moment_kinetics/src/coordinates.jl
  moment_kinetics/src/electron_kinetic_equation.jl
  moment_kinetics/src/gauss_legendre.jl
  moment_kinetics/src/hermite_spline_interpolation.jl
  moment_kinetics/src/initial_conditions.jl
  moment_kinetics/src/input_structs.jl
  moment_kinetics/src/interpolation.jl
  moment_kinetics/src/lagrange_polynomials.jl
  moment_kinetics/src/moment_kinetics_input.jl
  moment_kinetics/src/nonlinear_solvers.jl
  moment_kinetics/src/time_advance.jl
  moment_kinetics/test/interpolation_tests.jl
  moment_kinetics/test/jacobian_matrix_tests.jl
  moment_kinetics/test/nonlinear_solver_tests.jl
Labels: enhancement

#304 Revert downloaded HDF5 to 1.14.3
  machines/generic-batch-template/compile_dependencies.sh
  machines/generic-pc/compile_dependencies.sh
  machines/marconi/compile_dependencies.sh
Labels: bug

#303 Option for time evolution of electron distribution function
  .github/workflows/longtest.yml
  examples/kinetic-electrons/wall-bc_recyclefraction0.5_split3_kinetic-coarse_tails-KennedyCarpenterARK324-time-evolving-ge-wall-Jac.toml
  makie_post_processing/makie_post_processing/src/makie_post_processing.jl
  moment_kinetics/src/electron_fluid_equations.jl
  moment_kinetics/src/electron_kinetic_equation.jl
  moment_kinetics/src/electron_vpa_advection.jl
  moment_kinetics/src/external_sources.jl
  moment_kinetics/src/file_io.jl
  moment_kinetics/src/gauss_legendre.jl
  moment_kinetics/src/initial_conditions.jl
  moment_kinetics/src/input_structs.jl
  moment_kinetics/src/load_data.jl
  moment_kinetics/src/moment_kinetics_input.jl
  moment_kinetics/src/moment_kinetics_structs.jl
  moment_kinetics/src/nonlinear_solvers.jl
  moment_kinetics/src/runge_kutta.jl
  moment_kinetics/src/time_advance.jl
  moment_kinetics/test/kinetic_electron_tests.jl
  util/precompile_run.jl
  util/precompile_run_kinetic-electrons.jl
Labels: enhancement

#310 Fix a couple of small type instabilities
  moment_kinetics/src/initial_conditions.jl
  moment_kinetics/src/moment_kinetics_structs.jl
Labels: performance

#312 Add extra argument to get_species_input()
  test_scripts/gyroaverage_test.jl
Labels: bug

#313 Minor fix/optimisations for neutral wall bc
  moment_kinetics/src/boundary_conditions.jl
Labels: performance
